#!/usr/bin/python
import os
import subprocess
import argparse


WIFICONFIG = '''
#
# RPI-WIFI-CONF Autogenerated File
#

auto lo

iface lo inet loopback
iface eth0 inet dhcp

auto wlan0
allow-hotplug wlan0
iface wlan0 inet dhcp
  wpa-ssid "SSID_HERE"
  wpa-psk  "PASSWORD_HERE"
'''


def execute(cmd):
	proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
	output = []
	for line in iter(proc.stdout.readline,''):
		output += [line.rstrip()]
	proc.communicate()[0]
	proc.wait()
	return output

if __name__ == "__main__":
	with open("/etc/network/interfaces", "w") as f:
		f.write(WIFICONFIG)
	execute("sudo service hostapd stop")
	execute("sudo service dnsmasq stop")
	execute("sudo ifdown wlan0")
	execute("sudo ifup wlan0")