#! /bin/sh
# /etc/init.d/raspiwifi

### BEGIN INIT INFO
# Provides:          raspiwifi
# Required-Start:    $local_fs $syslog $network
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Control wifi on raspberry pi
# Description:       A NodeJS application to control wifi and ap on raspberry
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting panlhub daemon"
    cd /home/pi/raspiwifi/
    sleep 1
    sudo /usr/bin/node server.js >> /home/pi/raspiwifi/debug.log &
    echo $! > node.pid
    ;;
  stop)
    echo "Stopping panlhub daemon"
    PIDFile=/home/pi/raspiwifi/node.pid
    if [ -f $PIDFile ]; then
        sudo kill -9 $(cat $PIDFile)
        sudo kill -9 $(($(cat $PIDFile) + 1))
        sudo rm $PIDFile
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/raspiwifi {start|stop}"
    exit 1
    ;;
esac

exit 0

